### ISSUE TITLE
Add heredoc support

### ISSUE THREAD

**Issue by href** [asbjornenge/Docker.tmbundle#38]
Not sure if experimental features are of interest for this project, but I would assume Buildkit's heredoc support is here to stay:
https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/

This would be especially nice for the bash flavor of the syntax.

**Comment by ggari-robotnik** [comment]
I made this first try, but I'm far from undestanding how works everything,
It still have issues but you can try on my fork
https://github.com/ggari-robotnik/Docker.tmbundle

Any help will be appreciated

**Comment by fenollp** [comment]
Came here from https://github.com/jaytaylor/Dockerfile.sublime-syntax for the Sublime Text 3 support. (note the same issue is still open over at vscode: https://github.com/microsoft/vscode-containers/issues/108)

I'm not familiar with how to define tmbundle syntaxes but after trying @ggari-robotnik's fork (it's not working for me), maybe someone would like to try to use this definition of HEREDOC syntax from the Bash tmbundle?

https://github.com/sublimehq/Packages/blob/52c3ca948b2f0fae986bf8f6ae006b7ef3bc1437/ShellScript/Bash.sublime-syntax#L1698-L1807

**Comment by princemaple** [comment]
We already have this: https://github.com/asbjornenge/Docker.tmbundle/blob/master/Syntaxes/Dockerfile-bash.sublime-syntax

**Comment by iamkroot** [comment]
> We already have this: [`master`/Syntaxes/Dockerfile-bash.sublime-syntax](https://github.com/asbjornenge/Docker.tmbundle/blob/master/Syntaxes/Dockerfile-bash.sublime-syntax?rgh-link-date=2024-12-11T00%3A21%3A11Z)

That's not enough unfortunately. Here's an example of docker's heredoc syntax:
```dockerfile
RUN <<EOF
  echo hello
  cowsay moo
EOF

RUN echo this is a normal command
```

The current syntax of `Dockerfile-bash` assumes that anything that follows a directive (like `RUN`) is automatically in a JSON or bash scope. So in the above example, all of 
```bash
<<EOF
  echo hello
  cowsay moo
EOF
```
gets parsed in bash scope. Since `<<EOF` is also bash heredoc syntax, the lines inside get marked as simple `bash` strings rather than full commands.

We need something similar to what @ggari-robotnik has done above (a special case for `<<`) to get proper support.

**Comment by iamkroot** [comment]
Here's my attempt at this (building on https://github.com/ggari-robotnik/Docker.tmbundle from before)-
```yaml
        - match: \s*(<<)\s*([A-Za-z][A-Za-z0-9_]*)\s+
          captures:
            1: keyword.other.dockerfile
            2: entity.name.tag.dockerfile
          set: scope:source.shell.bash
          with_prototype:
            - include: scope:source.shell.bash#prototype
            - match: ^\2
              captures:
                0: entity.name.tag.dockerfile
              pop: true
```

This works for the most part-

![image](https://github.com/user-attachments/assets/61261072-a3f7-4376-b29b-d80a024d8f43)

But for whatever reason, it works incorrectly when the inner lines are not indented-

![image](https://github.com/user-attachments/assets/65ea68e7-8b9e-4786-afb2-6e793fc8aa3b)

I suspect it has something to do with how we are including the bash syntax, but I'm not too familiar with the format to fix this.
